credentials:
  usernames:
    v1:
      name: Vinícius Torres
      email: vinicius.torres@innovatismc.com
      password: senha1
    maysa:
      name: Maysa Barreiro
      email: contato@innovatismc.com
      password: senha2

cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name

preauthorized:
  emails:
    - melsby@gmail.com
