credentials:
  usernames:
    v1:
      name: Vinicius Torres
      email: vinicius.torres@innovatismc.com
      password: abc
    maysa:
      name: Maysa Barreiro
      email: contato@innovatismc.com
      password: def

cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name

preauthorized:
  emails:
    - vinicius.torres@innovatismc.com
    - contato@innovatismc.com
