[google]
client_email = "innovatis-data-science@innovatis-database.iam.gserviceaccount.com"
client_id = "106727989737135055409"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCX+86fpozzm7Pi
oUM7isb/Wf58LYGz2kh6Cmx0IOHJmnyK1NLi0dpJ1qCTIkMmeP3Ke4AOmDb6m8uU
...
-----END PRIVATE KEY-----'''
project_id = "innovatis-database"
