name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit
          pip install gspread oauth2client

      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/.streamlit/secrets.json

      - name: Deploy Streamlit app
        run: streamlit run app.py
