name: Ping Streamlit App

on:
  schedule:
    # roda a cada 10 horas (0, 10, 20 UTC)
    - cron: '0 */10 * * *'
  workflow_dispatch:   # opcional: permite disparo manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Streamlit URL
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://meu-app.streamlit.app || echo "falhou"
